import Question from "../components/Question.jsx";

const Faq = () => {
    return(
            <ul className="flex flex-col justify-between p-4 text-text1 bg-text2 rounded-md divide-y divide-grayishBlue2">
                <Question question={"¿Qué es P.I.T?"} awnser={"La terapia P.I.T. es un tratamiento no invasivo que se enfoca en reducir la inflamación de los nervios periféricos. Se basa en inyectar pequeñas cantidades de una solución de dextrosa diluida cerca de los nervios que están causando dolor. Esta solución disminuye la inflamación y promueve la regeneración nerviosa, lo que puede reducir el dolor de manera significativa."}/>
                <Question question={"¿Es doloroso el procedimiento?"} awnser={"La mayoría de los pacientes reportan que el dolor durante las inyecciones es mínimo o incluso inexistente. Las agujas utilizadas son muy finas y la solución inyectada no suele causar molestias. Es posible que sientas un leve pinchazo o una sensación de presión, pero la mayoría de las personas lo describen como bastante tolerable."}/>
                <Question question={"¿Puede tratar todo tipo de dolor?"} awnser={"La terapia P.I.T. es especialmente eficaz para el dolor neuropático, que se origina en los nervios. Esto incluye condiciones como la neuropatía, tendinitis, dolores articulares, y ciertos tipos de dolor crónico postquirúrgico. Sin embargo, no es un tratamiento para todos los tipos de dolor, por lo que es importante que hables con un médico especializado para evaluar si es adecuado para tu caso."}/>
                <Question question={"¿Cuántas sesiones necesito?"} awnser={"El número de sesiones depende de la gravedad de tu dolor y de cómo responda tu cuerpo al tratamiento. En muchos casos, los pacientes notan mejoría tras unas pocas sesiones, pero el alivio completo puede requerir varias sesiones, especialmente si el dolor ha sido persistente durante mucho tiempo."}/>
                <Question question={"¿Es seguro este tratamiento?"} awnser={"Sí, la terapia P.I.T. es segura. La solución inyectada es dextrosa diluida, un tipo de azúcar natural que no tiene efectos secundarios significativos. Como el procedimiento es mínimamente invasivo, los riesgos asociados son bajos en comparación con otros tratamientos como la cirugía o los medicamentos fuertes."}/>
                <Question question={"¿Cuánto tiempo tarda en hacer efecto?"} awnser={"Algunos pacientes experimentan alivio casi inmediato después de la primera sesión, mientras que otros pueden necesitar varias inyecciones antes de notar una mejora considerable. Todo depende de la condición que se esté tratando y de cómo reaccione tu cuerpo."}/>
                <Question question={"¿Hay algún efecto secundario?"} awnser={"En general, los efectos secundarios de la terapia P.I.T. son mínimos. Es posible que sientas algo de enrojecimiento o hinchazón en el lugar de la inyección, pero estos síntomas suelen desaparecer rápidamente. Es raro que se presenten complicaciones graves."}/>
                <Question question={"¿Es una solución permanente?"} awnser={"La duración del alivio del dolor varía de un paciente a otro. Algunas personas experimentan un alivio a largo plazo después de varias sesiones, mientras que otras pueden necesitar tratamientos de mantenimiento periódicos. Lo bueno es que la terapia P.I.T. Se puede repetir sin problemas, ya que no tiene los efectos secundarios adversos de otros tratamientos a largo plazo."}/>
                <Question question={"¿Cómo sé si soy un buen candidato para la P.I.T.?"} awnser={"La mejor manera de saber si la P.I.T. es adecuada para ti es consultar con tu médico de cabecera o con un especialista en el tratamiento del dolor. Él evaluará tu historial médico, los tipos de dolor que experimentas y si hay alguna contraindicación para este tipo de terapia."}/>
                <Question question={"¿Cómo me preparo para el tratamiento?"} awnser={"No se requiere ninguna preparación especial antes de la terapia P.I.T. Sin embargo, es recomendable que informes a tu médico sobre cualquier medicamento o suplemento que estés tomando para asegurarse de que no interfieran con el tratamiento. Después del procedimiento, puedes reanudar tus actividades diarias normales sin problemas."}/>
            </ul>
    )
}

export default Faq;